version: "3.7"

services:
    mongo:
        image: mongo
        restart: always
        volumes:
            - ./db-data:/data/db
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: dbpass
    backend:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        restart: always
        ports:
            - 5001:5001
        depends_on:
            - mongo
    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        ports:
            - 80:3000
        restart: always
        depends_on:
            - backend
